/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTurmasRouteImport } from './routes/_authenticated/turmas'
import { Route as AuthenticatedRegistrosRouteImport } from './routes/_authenticated/registros'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCuradoriaRouteImport } from './routes/_authenticated/curadoria'
import { Route as AuthenticatedComunicadosRouteImport } from './routes/_authenticated/comunicados'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedTurmasIndexRouteImport } from './routes/_authenticated/turmas.index'
import { Route as AuthenticatedTurmasClassIdRouteImport } from './routes/_authenticated/turmas.$classId'
import { Route as AuthenticatedAlunosStudentIdRouteImport } from './routes/_authenticated/alunos.$studentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTurmasRoute = AuthenticatedTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrosRoute = AuthenticatedRegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuradoriaRoute = AuthenticatedCuradoriaRouteImport.update({
  id: '/curadoria',
  path: '/curadoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunicadosRoute =
  AuthenticatedComunicadosRouteImport.update({
    id: '/comunicados',
    path: '/comunicados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTurmasIndexRoute =
  AuthenticatedTurmasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTurmasRoute,
  } as any)
const AuthenticatedTurmasClassIdRoute =
  AuthenticatedTurmasClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedTurmasRoute,
  } as any)
const AuthenticatedAlunosStudentIdRoute =
  AuthenticatedAlunosStudentIdRouteImport.update({
    id: '/alunos/$studentId',
    path: '/alunos/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/home': typeof AuthenticatedHomeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registros': typeof AuthenticatedRegistrosRoute
  '/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/alunos/$studentId': typeof AuthenticatedAlunosStudentIdRoute
  '/turmas/$classId': typeof AuthenticatedTurmasClassIdRoute
  '/turmas/': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/comunicados': typeof AuthenticatedComunicadosRoute
  '/curadoria': typeof AuthenticatedCuradoriaRoute
  '/home': typeof AuthenticatedHomeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registros': typeof AuthenticatedRegistrosRoute
  '/alunos/$studentId': typeof AuthenticatedAlunosStudentIdRoute
  '/turmas/$classId': typeof AuthenticatedTurmasClassIdRoute
  '/turmas': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/comunicados': typeof AuthenticatedComunicadosRoute
  '/_authenticated/curadoria': typeof AuthenticatedCuradoriaRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/registros': typeof AuthenticatedRegistrosRoute
  '/_authenticated/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/_authenticated/alunos/$studentId': typeof AuthenticatedAlunosStudentIdRoute
  '/_authenticated/turmas/$classId': typeof AuthenticatedTurmasClassIdRoute
  '/_authenticated/turmas/': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/comunicados'
    | '/curadoria'
    | '/home'
    | '/perfil'
    | '/registros'
    | '/turmas'
    | '/alunos/$studentId'
    | '/turmas/$classId'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/comunicados'
    | '/curadoria'
    | '/home'
    | '/perfil'
    | '/registros'
    | '/alunos/$studentId'
    | '/turmas/$classId'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/comunicados'
    | '/_authenticated/curadoria'
    | '/_authenticated/home'
    | '/_authenticated/perfil'
    | '/_authenticated/registros'
    | '/_authenticated/turmas'
    | '/_authenticated/alunos/$studentId'
    | '/_authenticated/turmas/$classId'
    | '/_authenticated/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/turmas': {
      id: '/_authenticated/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AuthenticatedTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registros': {
      id: '/_authenticated/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof AuthenticatedRegistrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curadoria': {
      id: '/_authenticated/curadoria'
      path: '/curadoria'
      fullPath: '/curadoria'
      preLoaderRoute: typeof AuthenticatedCuradoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunicados': {
      id: '/_authenticated/comunicados'
      path: '/comunicados'
      fullPath: '/comunicados'
      preLoaderRoute: typeof AuthenticatedComunicadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turmas/': {
      id: '/_authenticated/turmas/'
      path: '/'
      fullPath: '/turmas/'
      preLoaderRoute: typeof AuthenticatedTurmasIndexRouteImport
      parentRoute: typeof AuthenticatedTurmasRoute
    }
    '/_authenticated/turmas/$classId': {
      id: '/_authenticated/turmas/$classId'
      path: '/$classId'
      fullPath: '/turmas/$classId'
      preLoaderRoute: typeof AuthenticatedTurmasClassIdRouteImport
      parentRoute: typeof AuthenticatedTurmasRoute
    }
    '/_authenticated/alunos/$studentId': {
      id: '/_authenticated/alunos/$studentId'
      path: '/alunos/$studentId'
      fullPath: '/alunos/$studentId'
      preLoaderRoute: typeof AuthenticatedAlunosStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTurmasRouteChildren {
  AuthenticatedTurmasClassIdRoute: typeof AuthenticatedTurmasClassIdRoute
  AuthenticatedTurmasIndexRoute: typeof AuthenticatedTurmasIndexRoute
}

const AuthenticatedTurmasRouteChildren: AuthenticatedTurmasRouteChildren = {
  AuthenticatedTurmasClassIdRoute: AuthenticatedTurmasClassIdRoute,
  AuthenticatedTurmasIndexRoute: AuthenticatedTurmasIndexRoute,
}

const AuthenticatedTurmasRouteWithChildren =
  AuthenticatedTurmasRoute._addFileChildren(AuthenticatedTurmasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedComunicadosRoute: typeof AuthenticatedComunicadosRoute
  AuthenticatedCuradoriaRoute: typeof AuthenticatedCuradoriaRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRegistrosRoute: typeof AuthenticatedRegistrosRoute
  AuthenticatedTurmasRoute: typeof AuthenticatedTurmasRouteWithChildren
  AuthenticatedAlunosStudentIdRoute: typeof AuthenticatedAlunosStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedComunicadosRoute: AuthenticatedComunicadosRoute,
  AuthenticatedCuradoriaRoute: AuthenticatedCuradoriaRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRegistrosRoute: AuthenticatedRegistrosRoute,
  AuthenticatedTurmasRoute: AuthenticatedTurmasRouteWithChildren,
  AuthenticatedAlunosStudentIdRoute: AuthenticatedAlunosStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
