/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTurmasRouteImport } from './routes/_authenticated/turmas'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedTurmasIndexRouteImport } from './routes/_authenticated/turmas.index'
import { Route as AuthenticatedTurmasClassIdRouteImport } from './routes/_authenticated/turmas.$classId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTurmasRoute = AuthenticatedTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTurmasIndexRoute =
  AuthenticatedTurmasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTurmasRoute,
  } as any)
const AuthenticatedTurmasClassIdRoute =
  AuthenticatedTurmasClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedTurmasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/turmas/$classId': typeof AuthenticatedTurmasClassIdRoute
  '/turmas/': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/turmas/$classId': typeof AuthenticatedTurmasClassIdRoute
  '/turmas': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/turmas': typeof AuthenticatedTurmasRouteWithChildren
  '/_authenticated/turmas/$classId': typeof AuthenticatedTurmasClassIdRoute
  '/_authenticated/turmas/': typeof AuthenticatedTurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/turmas'
    | '/turmas/$classId'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/home' | '/turmas/$classId' | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/turmas'
    | '/_authenticated/turmas/$classId'
    | '/_authenticated/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/turmas': {
      id: '/_authenticated/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AuthenticatedTurmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/turmas/': {
      id: '/_authenticated/turmas/'
      path: '/'
      fullPath: '/turmas/'
      preLoaderRoute: typeof AuthenticatedTurmasIndexRouteImport
      parentRoute: typeof AuthenticatedTurmasRoute
    }
    '/_authenticated/turmas/$classId': {
      id: '/_authenticated/turmas/$classId'
      path: '/$classId'
      fullPath: '/turmas/$classId'
      preLoaderRoute: typeof AuthenticatedTurmasClassIdRouteImport
      parentRoute: typeof AuthenticatedTurmasRoute
    }
  }
}

interface AuthenticatedTurmasRouteChildren {
  AuthenticatedTurmasClassIdRoute: typeof AuthenticatedTurmasClassIdRoute
  AuthenticatedTurmasIndexRoute: typeof AuthenticatedTurmasIndexRoute
}

const AuthenticatedTurmasRouteChildren: AuthenticatedTurmasRouteChildren = {
  AuthenticatedTurmasClassIdRoute: AuthenticatedTurmasClassIdRoute,
  AuthenticatedTurmasIndexRoute: AuthenticatedTurmasIndexRoute,
}

const AuthenticatedTurmasRouteWithChildren =
  AuthenticatedTurmasRoute._addFileChildren(AuthenticatedTurmasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedTurmasRoute: typeof AuthenticatedTurmasRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedTurmasRoute: AuthenticatedTurmasRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
